// 《道德經》 content pack for 聽&說 — one item per chapter, Chinese and
// English aligned sentence by sentence (line N of textEn ↔ line N of text).
//
// Chinese: the received (王弼) text as printed on ctext.org (their punctuation
// decides the sentence boundaries: every 。！？ ends a line). English: James
// Legge, Tâo Teh King (Sacred Books of the East vol. 39, 1891, public domain),
// as printed on ctext.org ("Dao" for "Tao"). Legge's chapter titles are left
// out. Where Legge fused two Chinese sentences into one English sentence, the
// English is split at the matching clause; the two lines that have no English
// counterpart at all (39 非乎？, 67 其細也夫！) are left blank.
//
// Regenerate: the aligned data lives in scripts/daodejing-aligned.json.

const CN_DIGITS = ['', '一', '二', '三', '四', '五', '六', '七', '八', '九'];
const cnNumber = (n) => {
  if (n < 10) return CN_DIGITS[n];
  const tens = Math.floor(n / 10), ones = n % 10;
  return (tens === 1 ? '十' : CN_DIGITS[tens] + '十') + (ones ? CN_DIGITS[ones] : '');
};
const chapterName = (n) => `第${cnNumber(n)}章`;

// [zh, en] pairs per chapter, chapters 1–81 in order.
const CHAPTERS = [
  [ // 1
    ["道可道，非常道。", "The Dao that can be trodden is not the enduring and unchanging Dao."],
    ["名可名，非常名。", "The name that can be named is not the enduring and unchanging name."],
    ["無名天地之始；有名萬物之母。", "(Conceived of as) having no name, it is the Originator of heaven and earth; (conceived of as) having a name, it is the Mother of all things."],
    ["故常無欲，以觀其妙；常有欲，以觀其徼。", "Always without desire we must be found, If its deep mystery we would sound; But if desire always within us be, Its outer fringe is all that we shall see."],
    ["此兩者，同出而異名，同謂之玄。", "Under these two aspects, it is really the same; but as development takes place, it receives the different names. Together we call them the Mystery."],
    ["玄之又玄，衆妙之門。", "Where the Mystery is the deepest is the gate of all that is subtle and wonderful."],
  ],
  [ // 2
    ["天下皆知美之為美，斯惡已。", "All in the world know the beauty of the beautiful, and in doing this they have (the idea of) what ugliness is;"],
    ["皆知善之為善，斯不善已。", "they all know the skill of the skilful, and in doing this they have (the idea of) what the want of skill is."],
    ["故有無相生，難易相成，長短相較，高下相傾，音聲相和，前後相隨。", "So it is that existence and non-existence give birth the one to (the idea of) the other; that difficulty and ease produce the one (the idea of) the other; that length and shortness fashion out the one the figure of the other; that (the ideas of) height and lowness arise from the contrast of the one with the other; that the musical notes and tones become harmonious through the relation of one with another; and that being before and behind give the idea of one following another."],
    ["是以聖人處無為之事，行不言之教；萬物作焉而不辭，生而不有。", "Therefore the sage manages affairs without doing anything, and conveys his instructions without the use of speech. All things spring up, and there is not one which declines to show itself; they grow, and there is no claim made for their ownership;"],
    ["為而不恃，功成而弗居。", "they go through their processes, and there is no expectation (of a reward for the results). The work is accomplished, and there is no resting in it (as an achievement)."],
    ["夫唯弗居，是以不去。", "The work is done, but how no one can see; 'Tis this that makes the power not cease to be."],
  ],
  [ // 3
    ["不尚賢，使民不爭；不貴難得之貨，使民不為盜；不見可欲，使心不亂。", "Not to value and employ men of superior ability is the way to keep the people from rivalry among themselves; not to prize articles which are difficult to procure is the way to keep them from becoming thieves; not to show them what is likely to excite their desires is the way to keep their minds from disorder."],
    ["是以聖人之治，虛其心，實其腹，弱其志，強其骨。", "Therefore the sage, in the exercise of his government, empties their minds, fills their bellies, weakens their wills, and strengthens their bones."],
    ["常使民無知無欲。", "He constantly (tries to) keep them without knowledge and without desire,"],
    ["使夫知者不敢為也。", "and where there are those who have knowledge, to keep them from presuming to act (on it)."],
    ["為無為，則無不治。", "When there is this abstinence from action, good order is universal."],
  ],
  [ // 4
    ["道沖而用之或不盈。", "The Dao is (like) the emptiness of a vessel; and in our employment of it we must be on our guard against all fulness."],
    ["淵兮似萬物之宗。", "How deep and unfathomable it is, as if it were the Honoured Ancestor of all things!"],
    ["挫其銳，解其紛，和其光，同其塵。", "We should blunt our sharp points, and unravel the complications of things; we should attemper our brightness, and bring ourselves into agreement with the obscurity of others."],
    ["湛兮似或存。", "How pure and still the Dao is, as if it would ever so continue!"],
    ["吾不知誰之子，象帝之先。", "I do not know whose son it is. It might appear to have been before God."],
  ],
  [ // 5
    ["天地不仁，以萬物為芻狗；聖人不仁，以百姓為芻狗。", "Heaven and earth do not act from (the impulse of) any wish to be benevolent; they deal with all things as the dogs of grass are dealt with. The sages do not act from (any wish to be) benevolent; they deal with the people as the dogs of grass are dealt with."],
    ["天地之間，其猶橐籥乎？", "May not the space between heaven and earth be compared to a bellows?"],
    ["虛而不屈，動而愈出。", "'Tis emptied, yet it loses not its power; 'Tis moved again, and sends forth air the more."],
    ["多言數窮，不如守中。", "Much speech to swift exhaustion lead we see; Your inner being guard, and keep it free."],
  ],
  [ // 6
    ["谷神不死，是謂玄牝。", "The valley spirit dies not, aye the same; The female mystery thus do we name."],
    ["玄牝之門，是謂天地根。", "Its gate, from which at first they issued forth, Is called the root from which grew heaven and earth."],
    ["綿綿若存，用之不勤。", "Long and unbroken does its power remain, Used gently, and without the touch of pain."],
  ],
  [ // 7
    ["天長地久。", "Heaven is long-enduring and earth continues long."],
    ["天地所以能長且久者，以其不自生，故能長生。", "The reason why heaven and earth are able to endure and continue thus long is because they do not live of, or for, themselves. This is how they are able to continue and endure."],
    ["是以聖人後其身而身先；外其身而身存。", "Therefore the sage puts his own person last, and yet it is found in the foremost place; he treats his person as if it were foreign to him, and yet that person is preserved."],
    ["非以其無私耶？", "Is it not because he has no personal and private ends,"],
    ["故能成其私。", "that therefore such ends are realised?"],
  ],
  [ // 8
    ["上善若水。", "The highest excellence is like (that of) water."],
    ["水善利萬物而不爭，處衆人之所惡，故幾於道。", "The excellence of water appears in its benefiting all things, and in its occupying, without striving (to the contrary), the low place which all men dislike. Hence (its way) is near to (that of) the Dao."],
    ["居善地，心善淵，與善仁，言善信，正善治，事善能，動善時。", "The excellence of a residence is in (the suitability of) the place; that of the mind is in abysmal stillness; that of associations is in their being with the virtuous; that of words is in their trustworthiness; that of government is in its securing good order; that of (the conduct of) affairs is in its ability; and that of (the initiation of) any movement is in its timeliness."],
    ["夫唯不爭，故無尤。", "And when (one with the highest excellence) does not wrangle (about his low position), no one finds fault with him."],
  ],
  [ // 9
    ["持而盈之，不如其已；揣而銳之，不可長保。", "It is better to leave a vessel unfilled, than to attempt to carry it when it is full. If you keep feeling a point that has been sharpened, the point cannot long preserve its sharpness."],
    ["金玉滿堂，莫之能守；富貴而驕，自遺其咎。", "When gold and jade fill the hall, their possessor cannot keep them safe. When wealth and honours lead to arrogancy, this brings its evil on itself."],
    ["功遂身退天之道。", "When the work is done, and one's name is becoming distinguished, to withdraw into obscurity is the way of Heaven."],
  ],
  [ // 10
    ["載營魄抱一，能無離乎？", "When the intelligent and animal souls are held together in one embrace, they can be kept from separating."],
    ["專氣致柔，能嬰兒乎？", "When one gives undivided attention to the (vital) breath, and brings it to the utmost degree of pliancy, he can become as a (tender) babe."],
    ["滌除玄覽，能無疵乎？", "When he has cleansed away the most mysterious sights (of his imagination), he can become without a flaw."],
    ["愛民治國，能無知乎？", "In loving the people and ruling the state, cannot he proceed without any (purpose of) action?"],
    ["天門開闔，能為雌乎？", "In the opening and shutting of his gates of heaven, cannot he do so as a female bird?"],
    ["明白四達，能無知乎？", "While his intelligence reaches in every direction, cannot he (appear to) be without knowledge?"],
    ["生之、畜之，生而不有，為而不恃，長而不宰，是謂玄德。", "(The Dao) produces (all things) and nourishes them; it produces them and does not claim them as its own; it does all, and yet does not boast of it; it presides over all, and yet does not control them. This is what is called 'The mysterious Quality' (of the Dao)."],
  ],
  [ // 11
    ["三十輻，共一轂，當其無，有車之用。", "The thirty spokes unite in the one nave; but it is on the empty space (for the axle), that the use of the wheel depends."],
    ["埏埴以為器，當其無，有器之用。", "Clay is fashioned into vessels; but it is on their empty hollowness, that their use depends."],
    ["鑿戶牖以為室，當其無，有室之用。", "The door and windows are cut out (from the walls) to form an apartment; but it is on the empty space (within), that its use depends."],
    ["故有之以為利，無之以為用。", "Therefore, what has a (positive) existence serves for profitable adaptation, and what has not that for (actual) usefulness."],
  ],
  [ // 12
    ["五色令人目盲；五音令人耳聾；五味令人口爽；馳騁田獵，令人心發狂；難得之貨，令人行妨。", "Colour's five hues from the eyes their sight will take; Music's five notes the ears as deaf can make; The flavours five deprive the mouth of taste; The chariot course, and the wild hunting waste Make mad the mind; and objects rare and strange, Sought for, men's conduct will to evil change."],
    ["是以聖人為腹不為目，故去彼取此。", "Therefore the sage seeks to satisfy (the craving of) the belly, and not the (insatiable longing of the) eyes. He puts from him the latter, and prefers to seek the former."],
  ],
  [ // 13
    ["寵辱若驚，貴大患若身。", "Favour and disgrace would seem equally to be feared; honour and great calamity, to be regarded as personal conditions (of the same kind)."],
    ["何謂寵辱若驚？", "What is meant by speaking thus of favour and disgrace?"],
    ["寵為下，得之若驚，失之若驚，是謂寵辱若驚。", "Disgrace is being in a low position (after the enjoyment of favour). The getting that (favour) leads to the apprehension (of losing it), and the losing it leads to the fear of (still greater calamity) - this is what is meant by saying that favour and disgrace would seem equally to be feared."],
    ["何謂貴大患若身？", "And what is meant by saying that honour and great calamity are to be (similarly) regarded as personal conditions?"],
    ["吾所以有大患者，為吾有身，及吾無身，吾有何患？", "What makes me liable to great calamity is my having the body (which I call myself); if I had not the body, what great calamity could come to me?"],
    ["故貴以身為天下，若可寄天下；愛以身為天下，若可託天下。", "Therefore he who would administer the kingdom, honouring it as he honours his own person, may be employed to govern it, and he who would administer it with the love which he bears to his own person may be entrusted with it."],
  ],
  [ // 14
    ["視之不見，名曰夷；聽之不聞，名曰希；搏之不得，名曰微。", "We look at it, and we do not see it, and we name it 'the Equable.' We listen to it, and we do not hear it, and we name it 'the Inaudible.' We try to grasp it, and do not get hold of it, and we name it 'the Subtle.'"],
    ["此三者不可致詰，故混而為一。", "With these three qualities, it cannot be made the subject of description; and hence we blend them together and obtain The One."],
    ["其上不皦，其下不昧。", "Its upper part is not bright, and its lower part is not obscure."],
    ["繩繩不可名，復歸於無物。", "Ceaseless in its action, it yet cannot be named, and then it again returns and becomes nothing."],
    ["是謂無狀之狀，無物之象，是謂惚恍。", "This is called the Form of the Formless, and the Semblance of the Invisible; this is called the Fleeting and Indeterminable."],
    ["迎之不見其首，隨之不見其後。", "We meet it and do not see its Front; we follow it, and do not see its Back."],
    ["執古之道，以御今之有。", "When we can lay hold of the Dao of old to direct the things of the present day,"],
    ["能知古始，是謂道紀。", "and are able to know it as it was of old in the beginning, this is called (unwinding) the clue of Dao."],
  ],
  [ // 15
    ["古之善為士者，微妙玄通，深不可識。", "The skilful masters (of the Dao) in old times, with a subtle and exquisite penetration, comprehended its mysteries, and were deep (also) so as to elude men's knowledge."],
    ["夫唯不可識，故強為之容。", "As they were thus beyond men's knowledge, I will make an effort to describe of what sort they appeared to be."],
    ["豫兮若冬涉川；猶兮若畏四鄰；儼兮其若容；渙兮若冰之將釋；敦兮其若樸；曠兮其若谷；混兮其若濁；孰能濁以靜之徐清？", "Shrinking looked they like those who wade through a stream in winter; irresolute like those who are afraid of all around them; grave like a guest (in awe of his host); evanescent like ice that is melting away; unpretentious like wood that has not been fashioned into anything; vacant like a valley, and dull like muddy water. Who can (make) the muddy water (clear)? Let it be still, and it will gradually become clear."],
    ["孰能安以久動之徐生？", "Who can secure the condition of rest? Let movement go on, and the condition of rest will gradually arise."],
    ["保此道者，不欲盈。", "They who preserve this method of the Dao do not wish to be full (of themselves)."],
    ["夫唯不盈，故能蔽不新成。", "It is through their not being full of themselves that they can afford to seem worn and not appear new and complete."],
  ],
  [ // 16
    ["致虛極，守靜篤。", "The (state of) vacancy should be brought to the utmost degree, and that of stillness guarded with unwearying vigour."],
    ["萬物並作，吾以觀復。", "All things alike go through their processes of activity, and (then) we see them return (to their original state)."],
    ["夫物芸芸，各復歸其根。", "When things (in the vegetable world) have displayed their luxuriant growth, we see each of them return to its root."],
    ["歸根曰靜，是謂復命。", "This returning to their root is what we call the state of stillness; and that stillness may be called a reporting that they have fulfilled their appointed end."],
    ["復命曰常，知常曰明。", "The report of that fulfilment is the regular, unchanging rule. To know that unchanging rule is to be intelligent;"],
    ["不知常，妄作凶。", "not to know it leads to wild movements and evil issues."],
    ["知常容，容乃公，公乃王，王乃天，天乃道，道乃久，沒身不殆。", "The knowledge of that unchanging rule produces a (grand) capacity and forbearance, and that capacity and forbearance lead to a community (of feeling with all things). From this community of feeling comes a kingliness of character; and he who is king-like goes on to be heaven-like. In that likeness to heaven he possesses the Dao. Possessed of the Dao, he endures long; and to the end of his bodily life, is exempt from all danger of decay."],
  ],
  [ // 17
    ["太上，下知有之；其次，親而譽之；其次，畏之；其次，侮之。", "In the highest antiquity, (the people) did not know that there were (their rulers). In the next age they loved them and praised them. In the next they feared them; in the next they despised them."],
    ["信不足，焉有不信焉。", "Thus it was that when faith (in the Dao) was deficient (in the rulers) a want of faith in them ensued (in the people)."],
    ["悠兮，其貴言。", "How irresolute did those (earliest rulers) appear, showing (by their reticence) the importance which they set upon their words!"],
    ["功成事遂，百姓皆謂我自然。", "Their work was done and their undertakings were successful, while the people all said, 'We are as we are, of ourselves!'"],
  ],
  [ // 18
    ["大道廢，有仁義；智慧出，有大偽；六親不和，有孝慈；國家昏亂，有忠臣。", "When the Great Dao (Way or Method) ceased to be observed, benevolence and righteousness came into vogue. (Then) appeared wisdom and shrewdness, and there ensued great hypocrisy. When harmony no longer prevailed throughout the six kinships, filial sons found their manifestation; when the states and clans fell into disorder, loyal ministers appeared."],
  ],
  [ // 19
    ["絕聖棄智，民利百倍；絕仁棄義，民復孝慈；絕巧棄利，盜賊無有。", "If we could renounce our sageness and discard our wisdom, it would be better for the people a hundredfold. If we could renounce our benevolence and discard our righteousness, the people would again become filial and kindly. If we could renounce our artful contrivances and discard our (scheming for) gain, there would be no thieves nor robbers."],
    ["此三者以為文不足。", "Those three methods (of government) Thought olden ways in elegance did fail And made these names their want of worth to veil;"],
    ["故令有所屬：見素抱樸，少私寡欲。", "But simple views, and courses plain and true Would selfish ends and many lusts eschew."],
  ],
  [ // 20
    ["絕學無憂，唯之與阿，相去幾何？", "When we renounce learning we have no troubles. The (ready) 'yes,' and (flattering) 'yea;' Small is the difference they display."],
    ["善之與惡，相去若何？", "But mark their issues, good and ill; What space the gulf between shall fill?"],
    ["人之所畏，不可不畏。", "What all men fear is indeed to be feared;"],
    ["荒兮其未央哉！", "but how wide and without end is the range of questions (asking to be discussed)!"],
    ["衆人熙熙，如享太牢，如春登臺。", "The multitude of men look satisfied and pleased; as if enjoying a full banquet, as if mounted on a tower in spring."],
    ["我獨怕兮其未兆；如嬰兒之未孩；儽儽兮若無所歸。", "I alone seem listless and still, my desires having as yet given no indication of their presence. I am like an infant which has not yet smiled. I look dejected and forlorn, as if I had no home to go to."],
    ["衆人皆有餘，而我獨若遺。", "The multitude of men all have enough and to spare. I alone seem to have lost everything."],
    ["我愚人之心也哉！", "My mind is that of a stupid man;"],
    ["沌沌兮，俗人昭昭，我獨若昏。", "I am in a state of chaos. Ordinary men look bright and intelligent, while I alone seem to be benighted."],
    ["俗人察察，我獨悶悶。", "They look full of discrimination, while I alone am dull and confused."],
    ["澹兮其若海，飂兮若無止，衆人皆有以，而我獨頑似鄙。", "I seem to be carried about as on the sea, drifting as if I had nowhere to rest. All men have their spheres of action, while I alone seem dull and incapable, like a rude borderer."],
    ["我獨異於人，而貴食母。", "(Thus) I alone am different from other men, but I value the nursing-mother (the Dao)."],
  ],
  [ // 21
    ["孔德之容，唯道是從。", "The grandest forms of active force From Dao come, their only source."],
    ["道之為物，唯恍唯惚。", "Who can of Dao the nature tell? Our sight it flies, our touch as well."],
    ["忽兮恍兮，其中有象；恍兮忽兮，其中有物。", "Eluding sight, eluding touch, The forms of things all in it crouch; Eluding touch, eluding sight, There are their semblances, all right."],
    ["窈兮冥兮，其中有精；其精甚真，其中有信。", "Profound it is, dark and obscure; Things' essences all there endure. Those essences the truth enfold Of what, when seen, shall then be told."],
    ["自古及今，其名不去，以閱衆甫。", "Now it is so; 'twas so of old. Its name - what passes not away; So, in their beautiful array, Things form and never know decay."],
    ["吾何以知衆甫之狀哉？", "How know I that it is so with all the beauties of existing things?"],
    ["以此。", "By this (nature of the Dao)."],
  ],
  [ // 22
    ["曲則全，枉則直，窪則盈，弊則新，少則得，多則惑。", "The partial becomes complete; the crooked, straight; the empty, full; the worn out, new. He whose (desires) are few gets them; he whose (desires) are many goes astray."],
    ["是以聖人抱一為天下式。", "Therefore the sage holds in his embrace the one thing (of humility), and manifests it to all the world."],
    ["不自見，故明；不自是，故彰；不自伐，故有功；不自矜，故長。", "He is free from self- display, and therefore he shines; from self-assertion, and therefore he is distinguished; from self-boasting, and therefore his merit is acknowledged; from self-complacency, and therefore he acquires superiority."],
    ["夫唯不爭，故天下莫能與之爭。", "It is because he is thus free from striving that therefore no one in the world is able to strive with him."],
    ["古之所謂曲則全者，豈虛言哉！", "That saying of the ancients that 'the partial becomes complete' was not vainly spoken:"],
    ["誠全而歸之。", "all real completion is comprehended under it."],
  ],
  [ // 23
    ["希言自然，故飄風不終朝，驟雨不終日。", "Abstaining from speech marks him who is obeying the spontaneity of his nature. A violent wind does not last for a whole morning; a sudden rain does not last for the whole day."],
    ["孰為此者？", "To whom is it that these (two) things are owing?"],
    ["天地。", "To Heaven and Earth."],
    ["天地尚不能久，而況於人乎？", "If Heaven and Earth cannot make such (spasmodic) actings last long, how much less can man!"],
    ["故從事於道者，道者，同於道；德者，同於德；失者，同於失。", "Therefore when one is making the Dao his business, those who are also pursuing it, agree with him in it, and those who are making the manifestation of its course their object agree with him in that; while even those who are failing in both these things agree with him where they fail."],
    ["同於道者，道亦樂得之；同於德者，德亦樂得之；同於失者，失亦樂得之。", "Hence, those with whom he agrees as to the Dao have the happiness of attaining to it; those with whom he agrees as to its manifestation have the happiness of attaining to it; and those with whom he agrees in their failure have also the happiness of attaining (to the Dao)."],
    ["信不足，焉有不信焉。", "(But) when there is not faith sufficient (on his part), a want of faith (in him) ensues (on the part of the others)."],
  ],
  [ // 24
    ["企者不立；跨者不行；自見者不明；自是者不彰；自伐者無功；自矜者不長。", "He who stands on his tiptoes does not stand firm; he who stretches his legs does not walk (easily). (So), he who displays himself does not shine; he who asserts his own views is not distinguished; he who vaunts himself does not find his merit acknowledged; he who is self- conceited has no superiority allowed to him."],
    ["其在道也，曰：餘食贅行。", "Such conditions, viewed from the standpoint of the Dao, are like remnants of food, or a tumour on the body, which all dislike."],
    ["物或惡之，故有道者不處。", "Hence those who pursue (the course) of the Dao do not adopt and allow them."],
  ],
  [ // 25
    ["有物混成，先天地生。", "There was something undefined and complete, coming into existence before Heaven and Earth."],
    ["寂兮寥兮，獨立不改，周行而不殆，可以為天下母。", "How still it was and formless, standing alone, and undergoing no change, reaching everywhere and in no danger (of being exhausted)! It may be regarded as the Mother of all things."],
    ["吾不知其名，字之曰道，強為之名曰大。", "I do not know its name, and I give it the designation of the Dao (the Way or Course). Making an effort (further) to give it a name I call it The Great."],
    ["大曰逝，逝曰遠，遠曰反。", "Great, it passes on (in constant flow). Passing on, it becomes remote. Having become remote, it returns."],
    ["故道大，天大，地大，王亦大。", "Therefore the Dao is great; Heaven is great; Earth is great; and the (sage) king is also great."],
    ["域中有四大，而王居其一焉。", "In the universe there are four that are great, and the (sage) king is one of them."],
    ["人法地，地法天，天法道，道法自然。", "Man takes his law from the Earth; the Earth takes its law from Heaven; Heaven takes its law from the Dao. The law of the Dao is its being what it is."],
  ],
  [ // 26
    ["重為輕根，靜為躁君。", "Gravity is the root of lightness; stillness, the ruler of movement."],
    ["是以聖人終日行不離輜重。", "Therefore a wise prince, marching the whole day, does not go far from his baggage waggons."],
    ["雖有榮觀，燕處超然。", "Although he may have brilliant prospects to look at, he quietly remains (in his proper place), indifferent to them."],
    ["奈何萬乘之主，而以身輕天下？", "How should the lord of a myriad chariots carry himself lightly before the kingdom?"],
    ["輕則失本，躁則失君。", "If he do act lightly, he has lost his root (of gravity); if he proceed to active movement, he will lose his throne."],
  ],
  [ // 27
    ["善行無轍迹，善言無瑕讁；善數不用籌策；善閉無關楗而不可開，善結無繩約而不可解。", "The skilful traveller leaves no traces of his wheels or footsteps; the skilful speaker says nothing that can be found fault with or blamed; the skilful reckoner uses no tallies; the skilful closer needs no bolts or bars, while to open what he has shut will be impossible; the skilful binder uses no strings or knots, while to unloose what he has bound will be impossible."],
    ["是以聖人常善救人，故無棄人；常善救物，故無棄物。", "In the same way the sage is always skilful at saving men, and so he does not cast away any man; he is always skilful at saving things, and so he does not cast away anything."],
    ["是謂襲明。", "This is called 'Hiding the light of his procedure.'"],
    ["故善人者，不善人之師；不善人者，善人之資。", "Therefore the man of skill is a master (to be looked up to) by him who has not the skill; and he who has not the skill is the helper of (the reputation of) him who has the skill."],
    ["不貴其師，不愛其資，雖智大迷，是謂要妙。", "If the one did not honour his master, and the other did not rejoice in his helper, an (observer), though intelligent, might greatly err about them. This is called 'The utmost degree of mystery.'"],
  ],
  [ // 28
    ["知其雄，守其雌，為天下谿。", "Who knows his manhood's strength, Yet still his female feebleness maintains; As to one channel flow the many drains, All come to him, yea, all beneath the sky."],
    ["為天下谿，常德不離，復歸於嬰兒。", "Thus he the constant excellence retains; The simple child again, free from all stains."],
    ["知其白，守其黑，為天下式。", "Who knows how white attracts, Yet always keeps himself within black's shade, The pattern of humility displayed,"],
    ["為天下式，常德不忒，復歸於無極。", "Displayed in view of all beneath the sky; He in the unchanging excellence arrayed, Endless return to man's first state has made."],
    ["知其榮，守其辱，為天下谷。", "Who knows how glory shines, Yet loves disgrace, nor ever for it is pale; Behold his presence in a spacious vale, To which men come from all beneath the sky."],
    ["為天下谷，常德乃足，復歸於樸。", "The unchanging excellence completes its tale; The simple infant man in him we hail."],
    ["樸散則為器，聖人用之，則為官長，故大制不割。", "The unwrought material, when divided and distributed, forms vessels. The sage, when employed, becomes the Head of all the Officers (of government); and in his greatest regulations he employs no violent measures."],
  ],
  [ // 29
    ["將欲取天下而為之，吾見其不得已。", "If any one should wish to get the kingdom for himself, and to effect this by what he does, I see that he will not succeed."],
    ["天下神器，不可為也，為者敗之，執者失之。", "The kingdom is a spirit-like thing, and cannot be got by active doing. He who would so win it destroys it; he who would hold it in his grasp loses it."],
    ["故物或行或隨；或歔或吹；或強或羸；或挫或隳。", "The course and nature of things is such that What was in front is now behind; What warmed anon we freezing find. Strength is of weakness oft the spoil; The store in ruins mocks our toil."],
    ["是以聖人去甚，去奢，去泰。", "Hence the sage puts away excessive effort, extravagance, and easy indulgence."],
  ],
  [ // 30
    ["以道佐人主者，不以兵強天下。", "He who would assist a lord of men in harmony with the Dao will not assert his mastery in the kingdom by force of arms."],
    ["其事好還。", "Such a course is sure to meet with its proper return."],
    ["師之所處，荊棘生焉。", "Wherever a host is stationed, briars and thorns spring up."],
    ["大軍之後，必有凶年。", "In the sequence of great armies there are sure to be bad years."],
    ["善有果而已，不敢以取強。", "A skilful (commander) strikes a decisive blow, and stops. He does not dare (by continuing his operations) to assert and complete his mastery."],
    ["果而勿矜，果而勿伐，果而勿驕。", "He will strike the blow, but will be on his guard against being vain or boastful or arrogant in consequence of it."],
    ["果而不得已，果而勿強。", "He strikes it as a matter of necessity; he strikes it, but not from a wish for mastery."],
    ["物壯則老，是謂不道，不道早已。", "When things have attained their strong maturity they become old. This may be said to be not in accordance with the Dao: and what is not in accordance with it soon comes to an end."],
  ],
  [ // 31
    ["夫佳兵者，不祥之器，物或惡之，故有道者不處。", "Now arms, however beautiful, are instruments of evil omen, hateful, it may be said, to all creatures. Therefore they who have the Dao do not like to employ them."],
    ["君子居則貴左，用兵則貴右。", "The superior man ordinarily considers the left hand the most honourable place, but in time of war the right hand."],
    ["兵者不祥之器，非君子之器，不得已而用之，恬淡為上。", "Those sharp weapons are instruments of evil omen, and not the instruments of the superior man; - he uses them only on the compulsion of necessity. Calm and repose are what he prizes;"],
    ["勝而不美，而美之者，是樂殺人。", "victory (by force of arms) is to him undesirable. To consider this desirable would be to delight in the slaughter of men;"],
    ["夫樂殺人者，則不可以得志於天下矣。", "and he who delights in the slaughter of men cannot get his will in the kingdom."],
    ["吉事尚左，凶事尚右。", "On occasions of festivity to be on the left hand is the prized position; on occasions of mourning, the right hand."],
    ["偏將軍居左，上將軍居右，言以喪禮處之。", "The second in command of the army has his place on the left; the general commanding in chief has his on the right; - his place, that is, is assigned to him as in the rites of mourning."],
    ["殺人之衆，以哀悲泣之，戰勝以喪禮處之。", "He who has killed multitudes of men should weep for them with the bitterest grief; and the victor in battle has his place (rightly) according to those rites."],
  ],
  [ // 32
    ["道常無名。", "The Dao, considered as unchanging, has no name."],
    ["樸雖小，天下莫能臣也。", "Though in its primordial simplicity it may be small, the whole world dares not deal with (one embodying) it as a minister."],
    ["侯王若能守之，萬物將自賓。", "If a feudal prince or the king could guard and hold it, all would spontaneously submit themselves to him."],
    ["天地相合，以降甘露，民莫之令而自均。", "Heaven and Earth (under its guidance) unite together and send down the sweet dew, which, without the directions of men, reaches equally everywhere as of its own accord."],
    ["始制有名，名亦既有，夫亦將知止，知止所以不殆。", "As soon as it proceeds to action, it has a name. When it once has that name, (men) can know to rest in it. When they know to rest in it, they can be free from all risk of failure and error."],
    ["譬道之在天下，猶川谷之與江海。", "The relation of the Dao to all the world is like that of the great rivers and seas to the streams from the valleys."],
  ],
  [ // 33
    ["知人者智，自知者明。", "He who knows other men is discerning; he who knows himself is intelligent."],
    ["勝人者有力，自勝者強。", "He who overcomes others is strong; he who overcomes himself is mighty."],
    ["知足者富。", "He who is satisfied with his lot is rich;"],
    ["強行者有志。", "he who goes on acting with energy has a (firm) will."],
    ["不失其所者久。", "He who does not fail in the requirements of his position, continues long;"],
    ["死而不亡者壽。", "he who dies and yet does not perish, has longevity."],
  ],
  [ // 34
    ["大道汎兮，其可左右。", "All-pervading is the Great Dao! It may be found on the left hand and on the right."],
    ["萬物恃之而生而不辭，功成不名有。", "All things depend on it for their production, which it gives to them, not one refusing obedience to it. When its work is accomplished, it does not claim the name of having done it."],
    ["衣養萬物而不為主，常無欲，可名於小；萬物歸焉，而不為主，可名為大。", "It clothes all things as with a garment, and makes no assumption of being their lord; - it may be named in the smallest things. All things return (to their root and disappear), and do not know that it is it which presides over their doing so; - it may be named in the greatest things."],
    ["以其終不自為大，故能成其大。", "Hence the sage is able (in the same way) to accomplish his great achievements. It is through his not making himself great that he can accomplish them."],
  ],
  [ // 35
    ["執大象，天下往。", "To him who holds in his hands the Great Image (of the invisible Dao), the whole world repairs."],
    ["往而不害，安平大。", "Men resort to him, and receive no hurt, but (find) rest, peace, and the feeling of ease."],
    ["樂與餌，過客止。", "Music and dainties will make the passing guest stop (for a time)."],
    ["道之出口，淡乎其無味，視之不足見，聽之不足聞，用之不足既。", "But though the Dao as it comes from the mouth, seems insipid and has no flavour, though it seems not worth being looked at or listened to, the use of it is inexhaustible."],
  ],
  [ // 36
    ["將欲歙之，必固張之；將欲弱之，必固強之；將欲廢之，必固興之；將欲奪之，必固與之。", "When one is about to take an inspiration, he is sure to make a (previous) expiration; when he is going to weaken another, he will first strengthen him; when he is going to overthrow another, he will first have raised him up; when he is going to despoil another, he will first have made gifts to him:"],
    ["是謂微明。", "this is called 'Hiding the light (of his procedure).'"],
    ["柔弱勝剛強。", "The soft overcomes the hard; and the weak the strong."],
    ["魚不可脫於淵，國之利器不可以示人。", "Fishes should not be taken from the deep; instruments for the profit of a state should not be shown to the people."],
  ],
  [ // 37
    ["道常無為而無不為。", "The Dao in its regular course does nothing (for the sake of doing it), and so there is nothing which it does not do."],
    ["侯王若能守之，萬物將自化。", "If princes and kings were able to maintain it, all things would of themselves be transformed by them."],
    ["化而欲作，吾將鎮之以無名之樸。", "If this transformation became to me an object of desire, I would express the desire by the nameless simplicity."],
    ["無名之樸，夫亦將無欲。", "Simplicity without a name Is free from all external aim."],
    ["不欲以靜，天下將自定。", "With no desire, at rest and still, All things go right as of their will."],
  ],
  [ // 38
    ["上德不德，是以有德；下德不失德，是以無德。", "(Those who) possessed in highest degree the attributes (of the Dao) did not (seek) to show them, and therefore they possessed them (in fullest measure). (Those who) possessed in a lower degree those attributes (sought how) not to lose them, and therefore they did not possess them (in fullest measure)."],
    ["上德無為而無以為；下德為之而有以為。", "(Those who) possessed in the highest degree those attributes did nothing (with a purpose), and had no need to do anything. (Those who) possessed them in a lower degree were (always) doing, and had need to be so doing."],
    ["上仁為之而無以為；上義為之而有以為。", "(Those who) possessed the highest benevolence were (always seeking) to carry it out, and had no need to be doing so. (Those who) possessed the highest righteousness were (always seeking) to carry it out, and had need to be so doing."],
    ["上禮為之而莫之應，則攘臂而扔之。", "(Those who) possessed the highest (sense of) propriety were (always seeking) to show it, and when men did not respond to it, they bared the arm and marched up to them."],
    ["故失道而後德，失德而後仁，失仁而後義，失義而後禮。", "Thus it was that when the Dao was lost, its attributes appeared; when its attributes were lost, benevolence appeared; when benevolence was lost, righteousness appeared; and when righteousness was lost, the proprieties appeared."],
    ["夫禮者，忠信之薄，而亂之首。", "Now propriety is the attenuated form of leal-heartedness and good faith, and is also the commencement of disorder;"],
    ["前識者，道之華，而愚之始。", "swift apprehension is (only) a flower of the Dao, and is the beginning of stupidity."],
    ["是以大丈夫處其厚，不居其薄；處其實，不居其華。", "Thus it is that the Great man abides by what is solid, and eschews what is flimsy; dwells with the fruit and not with the flower."],
    ["故去彼取此。", "It is thus that he puts away the one and makes choice of the other."],
  ],
  [ // 39
    ["昔之得一者：天得一以清；地得一以寧；神得一以靈；谷得一以盈；萬物得一以生；侯王得一以為天下貞。", "The things which from of old have got the One (the Dao) are - Heaven which by it is bright and pure; Earth rendered thereby firm and sure; Spirits with powers by it supplied; Valleys kept full throughout their void All creatures which through it do live Princes and kings who from it get The model which to all they give."],
    ["其致之，天無以清，將恐裂；地無以寧，將恐發；神無以靈，將恐歇；谷無以盈，將恐竭；萬物無以生，將恐滅；侯王無以貴高將恐蹶。", "All these are the results of the One (Dao). If heaven were not thus pure, it soon would rend; If earth were not thus sure, 'twould break and bend; Without these powers, the spirits soon would fail; If not so filled, the drought would parch each vale; Without that life, creatures would pass away; Princes and kings, without that moral sway, However grand and high, would all decay."],
    ["故貴以賤為本，高以下為基。", "Thus it is that dignity finds its (firm) root in its (previous) meanness, and what is lofty finds its stability in the lowness (from which it rises)."],
    ["是以侯王自稱孤、寡、不穀。", "Hence princes and kings call themselves 'Orphans,' 'Men of small virtue,' and as 'Carriages without a nave.'"],
    ["此非以賤為本耶？", "Is not this an acknowledgment that in their considering themselves mean they see the foundation of their dignity?"],
    ["非乎？", ""],
    ["故致數譽無譽。", "So it is that in the enumeration of the different parts of a carriage we do not come on what makes it answer the ends of a carriage."],
    ["不欲琭琭如玉，珞珞如石。", "They do not wish to show themselves elegant-looking as jade, but (prefer) to be coarse-looking as an (ordinary) stone."],
  ],
  [ // 40
    ["反者道之動；弱者道之用。", "The movement of the Dao By contraries proceeds; And weakness marks the course Of Dao's mighty deeds."],
    ["天下萬物生於有，有生於無。", "All things under heaven sprang from It as existing (and named); that existence sprang from It as non- existent (and not named)."],
  ],
  [ // 41
    ["上士聞道，勤而行之；中士聞道，若存若亡；下士聞道，大笑之。", "Scholars of the highest class, when they hear about the Dao, earnestly carry it into practice. Scholars of the middle class, when they have heard about it, seem now to keep it and now to lose it. Scholars of the lowest class, when they have heard about it, laugh greatly at it."],
    ["不笑不足以為道。", "If it were not (thus) laughed at, it would not be fit to be the Dao."],
    ["故建言有之：明道若昧；進道若退；夷道若纇；上德若谷；太白若辱；廣德若不足；建德若偷；質真若渝；大方無隅；大器晚成；大音希聲；大象無形；道隱無名。", "Therefore the sentence-makers have thus expressed themselves: 'The Dao, when brightest seen, seems light to lack; Who progress in it makes, seems drawing back; Its even way is like a rugged track. Its highest virtue from the vale doth rise; Its greatest beauty seems to offend the eyes; And he has most whose lot the least supplies. Its firmest virtue seems but poor and low; Its solid truth seems change to undergo; Its largest square doth yet no corner show A vessel great, it is the slowest made; Loud is its sound, but never word it said; A semblance great, the shadow of a shade.' The Dao is hidden, and has no name;"],
    ["夫唯道，善貸且成。", "but it is the Dao which is skilful at imparting (to all things what they need) and making them complete."],
  ],
  [ // 42
    ["道生一，一生二，二生三，三生萬物。", "The Dao produced One; One produced Two; Two produced Three; Three produced All things."],
    ["萬物負陰而抱陽，沖氣以為和。", "All things leave behind them the Obscurity (out of which they have come), and go forward to embrace the Brightness (into which they have emerged), while they are harmonised by the Breath of Vacancy."],
    ["人之所惡，唯孤、寡、不穀，而王公以為稱。", "What men dislike is to be orphans, to have little virtue, to be as carriages without naves; and yet these are the designations which kings and princes use for themselves."],
    ["故物或損之而益，或益之而損。", "So it is that some things are increased by being diminished, and others are diminished by being increased."],
    ["人之所教，我亦教之。", "What other men (thus) teach, I also teach."],
    ["強梁者不得其死，吾將以為教父。", "The violent and strong do not die their natural death. I will make this the basis of my teaching."],
  ],
  [ // 43
    ["天下之至柔，馳騁天下之至堅。", "The softest thing in the world dashes against and overcomes the hardest;"],
    ["無有入無間，吾是以知無為之有益。", "that which has no (substantial) existence enters where there is no crevice. I know hereby what advantage belongs to doing nothing (with a purpose)."],
    ["不言之教，無為之益，天下希及之。", "There are few in the world who attain to the teaching without words, and the advantage arising from non-action."],
  ],
  [ // 44
    ["名與身孰親？", "Or fame or life, Which do you hold more dear?"],
    ["身與貨孰多？", "Or life or wealth, To which would you adhere?"],
    ["得與亡孰病？", "Keep life and lose those other things; Keep them and lose your life: - which brings Sorrow and pain more near?"],
    ["是故甚愛必大費；多藏必厚亡。", "Thus we may see, Who cleaves to fame Rejects what is more great; Who loves large stores Gives up the richer state."],
    ["知足不辱，知止不殆，可以長久。", "Who is content Needs fear no shame. Who knows to stop Incurs no blame. From danger free Long live shall he."],
  ],
  [ // 45
    ["大成若缺，其用不弊。", "Who thinks his great achievements poor Shall find his vigour long endure."],
    ["大盈若沖，其用不窮。", "Of greatest fulness, deemed a void, Exhaustion never shall stem the tide."],
    ["大直若屈，大巧若拙，大辯若訥。", "Do thou what's straight still crooked deem; Thy greatest art still stupid seem, And eloquence a stammering scream."],
    ["躁勝寒靜勝熱。", "Constant action overcomes cold; being still overcomes heat."],
    ["清靜為天下正。", "Purity and stillness give the correct law to all under heaven."],
  ],
  [ // 46
    ["天下有道，卻走馬以糞。", "When the Dao prevails in the world, they send back their swift horses to (draw) the dung- carts."],
    ["天下無道，戎馬生於郊。", "When the Dao is disregarded in the world, the war-horses breed in the border lands."],
    ["禍莫大於不知足；咎莫大於欲得。", "There is no guilt greater than to sanction ambition; no calamity greater than to be discontented with one's lot; no fault greater than the wish to be getting."],
    ["故知足之足，常足矣。", "Therefore the sufficiency of contentment is an enduring and unchanging sufficiency."],
  ],
  [ // 47
    ["不出戶知天下；不闚牖見天道。", "Without going outside his door, one understands (all that takes place) under the sky; without looking out from his window, one sees the Dao of Heaven."],
    ["其出彌遠，其知彌少。", "The farther that one goes out (from himself), the less he knows."],
    ["是以聖人不行而知，不見而名，不為而成。", "Therefore the sages got their knowledge without travelling; gave their (right) names to things without seeing them; and accomplished their ends without any purpose of doing so."],
  ],
  [ // 48
    ["為學日益，為道日損。", "He who devotes himself to learning (seeks) from day to day to increase (his knowledge); he who devotes himself to the Dao (seeks) from day to day to diminish (his doing)."],
    ["損之又損，以至於無為。", "He diminishes it and again diminishes it, till he arrives at doing nothing (on purpose)."],
    ["無為而無不為。", "Having arrived at this point of non-action, there is nothing which he does not do."],
    ["取天下常以無事，及其有事，不足以取天下。", "He who gets as his own all under heaven does so by giving himself no trouble (with that end). If one take trouble (with that end), he is not equal to getting as his own all under heaven."],
  ],
  [ // 49
    ["聖人無常心，以百姓心為心。", "The sage has no invariable mind of his own; he makes the mind of the people his mind."],
    ["善者，吾善之；不善者，吾亦善之；德善。", "To those who are good (to me), I am good; and to those who are not good (to me), I am also good; - and thus (all) get to be good."],
    ["信者，吾信之；不信者，吾亦信之；德信。", "To those who are sincere (with me), I am sincere; and to those who are not sincere (with me), I am also sincere; - and thus (all) get to be sincere."],
    ["聖人在天下，歙歙為天下渾其心，百姓皆注其耳目，聖人皆孩之。", "The sage has in the world an appearance of indecision, and keeps his mind in a state of indifference to all. The people all keep their eyes and ears directed to him, and he deals with them all as his children."],
  ],
  [ // 50
    ["出生入死。", "Men come forth and live; they enter (again) and die."],
    ["生之徒，十有三；死之徒，十有三；人之生，動之死地，十有三。", "Of every ten three are ministers of life (to themselves); and three are ministers of death. There are also three in every ten whose aim is to live, but whose movements tend to the land (or place) of death."],
    ["夫何故？", "And for what reason?"],
    ["以其生，生之厚。", "Because of their excessive endeavours to perpetuate life."],
    ["蓋聞善攝生者，陸行不遇兕虎，入軍不被甲兵；兕無所投其角，虎無所措其爪，兵無所容其刃。", "But I have heard that he who is skilful in managing the life entrusted to him for a time travels on the land without having to shun rhinoceros or tiger, and enters a host without having to avoid buff coat or sharp weapon. The rhinoceros finds no place in him into which to thrust its horn, nor the tiger a place in which to fix its claws, nor the weapon a place to admit its point."],
    ["夫何故？", "And for what reason?"],
    ["以其無死地。", "Because there is in him no place of death."],
  ],
  [ // 51
    ["道生之，德畜之，物形之，勢成之。", "All things are produced by the Dao, and nourished by its outflowing operation. They receive their forms according to the nature of each, and are completed according to the circumstances of their condition."],
    ["是以萬物莫不尊道而貴德。", "Therefore all things without exception honour the Dao, and exalt its outflowing operation."],
    ["道之尊，德之貴，夫莫之命常自然。", "This honouring of the Dao and exalting of its operation is not the result of any ordination, but always a spontaneous tribute."],
    ["故道生之，德畜之；長之育之；亭之毒之；養之覆之。", "Thus it is that the Dao produces (all things), nourishes them, brings them to their full growth, nurses them, completes them, matures them, maintains them, and overspreads them."],
    ["生而不有，為而不恃，長而不宰，是謂玄德。", "It produces them and makes no claim to the possession of them; it carries them through their processes and does not vaunt its ability in doing so; it brings them to maturity and exercises no control over them; - this is called its mysterious operation."],
  ],
  [ // 52
    ["天下有始，以為天下母。", "(The Dao) which originated all under the sky is to be considered as the mother of them all."],
    ["既得其母，以知其子，既知其子，復守其母，沒身不殆。", "When the mother is found, we know what her children should be. When one knows that he is his mother's child, and proceeds to guard (the qualities of) the mother that belong to him, to the end of his life he will be free from all peril."],
    ["塞其兌，閉其門，終身不勤。", "Let him keep his mouth closed, and shut up the portals (of his nostrils), and all his life he will be exempt from laborious exertion."],
    ["開其兌，濟其事，終身不救。", "Let him keep his mouth open, and (spend his breath) in the promotion of his affairs, and all his life there will be no safety for him."],
    ["見小曰明，守柔曰強。", "The perception of what is small is (the secret of clear- sightedness; the guarding of what is soft and tender is (the secret of) strength."],
    ["用其光，復歸其明，無遺身殃；是為習常。", "Who uses well his light, Reverting to its (source so) bright, Will from his body ward all blight, And hides the unchanging from men's sight."],
  ],
  [ // 53
    ["使我介然有知，行於大道，唯施是畏。", "If I were suddenly to become known, and (put into a position to) conduct (a government) according to the Great Dao, what I should be most afraid of would be a boastful display."],
    ["大道甚夷，而民好徑。", "The great Dao (or way) is very level and easy; but people love the by-ways."],
    ["朝甚除，田甚蕪，倉甚虛；服文綵，帶利劍，厭飲食，財貨有餘；是謂盜夸。", "Their court(-yards and buildings) shall be well kept, but their fields shall be ill-cultivated, and their granaries very empty. They shall wear elegant and ornamented robes, carry a sharp sword at their girdle, pamper themselves in eating and drinking, and have a superabundance of property and wealth; - such (princes) may be called robbers and boasters."],
    ["非道也哉！", "This is contrary to the Dao surely!"],
  ],
  [ // 54
    ["善建不拔，善抱者不脫，子孫以祭祀不輟。", "What (Dao's) skilful planter plants Can never be uptorn; What his skilful arms enfold, From him can never be borne. Sons shall bring in lengthening line, Sacrifices to his shrine."],
    ["修之於身，其德乃真；修之於家，其德乃餘；修之於鄉，其德乃長；修之於國，其德乃豐；修之於天下，其德乃普。", "Dao when nursed within one's self, His vigour will make true; And where the family it rules What riches will accrue! The neighbourhood where it prevails In thriving will abound; And when 'tis seen throughout the state, Good fortune will be found. Employ it the kingdom o'er, And men thrive all around."],
    ["故以身觀身，以家觀家，以鄉觀鄉，以國觀國，以天下觀天下。", "In this way the effect will be seen in the person, by the observation of different cases; in the family; in the neighbourhood; in the state; and in the kingdom."],
    ["吾何以知天下然哉？", "How do I know that this effect is sure to hold thus all under the sky?"],
    ["以此。", "By this (method of observation)."],
  ],
  [ // 55
    ["含德之厚，比於赤子。", "He who has in himself abundantly the attributes (of the Dao) is like an infant."],
    ["蜂蠆虺蛇不螫，猛獸不據，攫鳥不搏。", "Poisonous insects will not sting him; fierce beasts will not seize him; birds of prey will not strike him."],
    ["骨弱筋柔而握固。", "(The infant's) bones are weak and its sinews soft, but yet its grasp is firm."],
    ["未知牝牡之合而全作，精之至也。", "It knows not yet the union of male and female, and yet its virile member may be excited; - showing the perfection of its physical essence."],
    ["終日號而不嗄，和之至也。", "All day long it will cry without its throat becoming hoarse; - showing the harmony (in its constitution)."],
    ["知和曰常，知常曰明，益生曰祥。", "To him by whom this harmony is known, (The secret of) the unchanging (Dao) is shown, And in the knowledge wisdom finds its throne. All life-increasing arts to evil turn;"],
    ["心使氣曰強。", "Where the mind makes the vital breath to burn, (False) is the strength, (and o'er it we should mourn.)"],
    ["物壯則老，謂之不道，不道早已。", "When things have become strong, they (then) become old, which may be said to be contrary to the Dao. Whatever is contrary to the Dao soon ends."],
  ],
  [ // 56
    ["知者不言，言者不知。", "He who knows (the Dao) does not (care to) speak (about it); he who is (ever ready to) speak about it does not know it."],
    ["塞其兑，閉其門，挫其銳，解其分，和其光，同其塵，是謂玄同。", "He (who knows it) will keep his mouth shut and close the portals (of his nostrils). He will blunt his sharp points and unravel the complications of things; he will attemper his brightness, and bring himself into agreement with the obscurity (of others). This is called 'the Mysterious Agreement.'"],
    ["故不可得而親，不可得而踈；不可得而利，不可得而害；不可得而貴，不可得而賤。", "(Such an one) cannot be treated familiarly or distantly; he is beyond all consideration of profit or injury; beyond all consideration of nobility or meanness:"],
    ["故為天下貴。", "he is the noblest man under heaven."],
  ],
  [ // 57
    ["以正治國，以奇用兵，以無事取天下。", "A state may be ruled by (measures of) correction; weapons of war may be used with crafty dexterity; (but) the kingdom is made one's own (only) by freedom from action and purpose."],
    ["吾何以知其然哉？", "How do I know that it is so?"],
    ["以此：天下多忌諱，而民彌貧；民多利器，國家滋昏；人多伎巧，奇物滋起；法令滋彰，盜賊多有。", "By these facts: - In the kingdom the multiplication of prohibitive enactments increases the poverty of the people; the more implements to add to their profit that the people have, the greater disorder is there in the state and clan; the more acts of crafty dexterity that men possess, the more do strange contrivances appear; the more display there is of legislation, the more thieves and robbers there are."],
    ["故聖人云：我無為，而民自化；我好靜，而民自正；我無事，而民自富；我無欲，而民自樸。", "Therefore a sage has said, 'I will do nothing (of purpose), and the people will be transformed of themselves; I will be fond of keeping still, and the people will of themselves become correct. I will take no trouble about it, and the people will of themselves become rich; I will manifest no ambition, and the people will of themselves attain to the primitive simplicity.'"],
  ],
  [ // 58
    ["其政悶悶，其民淳淳；其政察察，其民缺缺。", "The government that seems the most unwise, Oft goodness to the people best supplies; That which is meddling, touching everything, Will work but ill, and disappointment bring."],
    ["禍兮福之所倚，福兮禍之所伏。", "Misery! - happiness is to be found by its side! Happiness! - misery lurks beneath it!"],
    ["孰知其極？", "Who knows what either will come to in the end?"],
    ["其無正。", "Shall we then dispense with correction?"],
    ["正復為奇，善復為妖。", "The (method of) correction shall by a turn become distortion, and the good in it shall by a turn become evil."],
    ["人之迷，其日固久。", "The delusion of the people (on this point) has indeed subsisted for a long time."],
    ["是以聖人方而不割，廉而不劌，直而不肆，光而不燿。", "Therefore the sage is (like) a square which cuts no one (with its angles); (like) a corner which injures no one (with its sharpness). He is straightforward, but allows himself no license; he is bright, but does not dazzle."],
  ],
  [ // 59
    ["治人事天莫若嗇。", "For regulating the human (in our constitution) and rendering the (proper) service to the heavenly, there is nothing like moderation."],
    ["夫唯嗇，是謂早服；早服謂之重積德；重積德則無不克；無不克則莫知其極；莫知其極，可以有國；有國之母，可以長久；是謂深根固柢，長生久視之道。", "It is only by this moderation that there is effected an early return (to man's normal state). That early return is what I call the repeated accumulation of the attributes (of the Dao). With that repeated accumulation of those attributes, there comes the subjugation (of every obstacle to such return). Of this subjugation we know not what shall be the limit; and when one knows not what the limit shall be, he may be the ruler of a state. He who possesses the mother of the state may continue long. His case is like that (of the plant) of which we say that its roots are deep and its flower stalks firm: - this is the way to secure that its enduring life shall long be seen."],
  ],
  [ // 60
    ["治大國若烹小鮮。", "Governing a great state is like cooking small fish."],
    ["以道蒞天下，其鬼不神；非其鬼不神，其神不傷人；非其神不傷人，聖人亦不傷人。", "Let the kingdom be governed according to the Dao, and the manes of the departed will not manifest their spiritual energy. It is not that those manes have not that spiritual energy, but it will not be employed to hurt men. It is not that it could not hurt men, but neither does the ruling sage hurt them."],
    ["夫兩不相傷，故德交歸焉。", "When these two do not injuriously affect each other, their good influences converge in the virtue (of the Dao)."],
  ],
  [ // 61
    ["大國者下流，天下之交，天下之牝。", "What makes a great state is its being (like) a low-lying, down- flowing (stream); - it becomes the centre to which tend (all the small states) under heaven."],
    ["牝常以靜勝牡，以靜為下。", "(To illustrate from) the case of all females: - the female always overcomes the male by her stillness. Stillness may be considered (a sort of) abasement."],
    ["故大國以下小國，則取小國；小國以下大國，則取大國。", "Thus it is that a great state, by condescending to small states, gains them for itself; and that small states, by abasing themselves to a great state, win it over to them."],
    ["故或下以取，或下而取。", "In the one case the abasement leads to gaining adherents, in the other case to procuring favour."],
    ["大國不過欲兼畜人，小國不過欲入事人。", "The great state only wishes to unite men together and nourish them; a small state only wishes to be received by, and to serve, the other."],
    ["夫兩者各得其所欲，大者宜為下。", "Each gets what it desires, but the great state must learn to abase itself."],
  ],
  [ // 62
    ["道者萬物之奧。", "Dao has of all things the most honoured place."],
    ["善人之寶，不善人之所保。", "No treasures give good men so rich a grace; Bad men it guards, and doth their ill efface."],
    ["美言可以市，尊行可以加人。", "(Its) admirable words can purchase honour; (its) admirable deeds can raise their performer above others."],
    ["人之不善，何棄之有？", "Even men who are not good are not abandoned by it."],
    ["故立天子，置三公，雖有拱璧以先駟馬，不如坐進此道。", "Therefore when the sovereign occupies his place as the Son of Heaven, and he has appointed his three ducal ministers, though (a prince) were to send in a round symbol-of-rank large enough to fill both the hands, and that as the precursor of the team of horses (in the court-yard), such an offering would not be equal to (a lesson of) this Dao, which one might present on his knees."],
    ["古之所以貴此道者何？", "Why was it that the ancients prized this Dao so much?"],
    ["不曰：以求得，有罪以免耶？", "Was it not because it could be got by seeking for it, and the guilty could escape (from the stain of their guilt) by it?"],
    ["故為天下貴。", "This is the reason why all under heaven consider it the most valuable thing."],
  ],
  [ // 63
    ["為無為，事無事，味無味。", "(It is the way of the Dao) to act without (thinking of) acting; to conduct affairs without (feeling the) trouble of them; to taste without discerning any flavour;"],
    ["大小多少，報怨以德。", "to consider what is small as great, and a few as many; and to recompense injury with kindness."],
    ["圖難於其易，為大於其細；天下難事，必作於易，天下大事，必作於細。", "(The master of it) anticipates things that are difficult while they are easy, and does things that would become great while they are small. All difficult things in the world are sure to arise from a previous state in which they were easy, and all great things from one in which they were small."],
    ["是以聖人終不為大，故能成其大。", "Therefore the sage, while he never does what is great, is able on that account to accomplish the greatest things."],
    ["夫輕諾必寡信，多易必多難。", "He who lightly promises is sure to keep but little faith; he who is continually thinking things easy is sure to find them difficult."],
    ["是以聖人猶難之，故終無難矣。", "Therefore the sage sees difficulty even in what seems easy, and so never has any difficulties."],
  ],
  [ // 64
    ["其安易持，其未兆易謀。", "That which is at rest is easily kept hold of; before a thing has given indications of its presence, it is easy to take measures against it;"],
    ["其脆易泮，其微易散。", "that which is brittle is easily broken; that which is very small is easily dispersed."],
    ["為之於未有，治之於未亂。", "Action should be taken before a thing has made its appearance; order should be secured before disorder has begun."],
    ["合抱之木，生於毫末；九層之臺，起於累土；千里之行，始於足下。", "The tree which fills the arms grew from the tiniest sprout; the tower of nine storeys rose from a (small) heap of earth; the journey of a thousand li commenced with a single step."],
    ["為者敗之，執者失之。", "He who acts (with an ulterior purpose) does harm; he who takes hold of a thing (in the same way) loses his hold."],
    ["是以聖人無為故無敗；無執故無失。", "The sage does not act (so), and therefore does no harm; he does not lay hold (so), and therefore does not lose his bold."],
    ["民之從事，常於幾成而敗之。", "(But) people in their conduct of affairs are constantly ruining them when they are on the eve of success."],
    ["慎終如始，則無敗事，是以聖人欲不欲，不貴難得之貨；學不學，復衆人之所過，以輔萬物之自然，而不敢為。", "If they were careful at the end, as (they should be) at the beginning, they would not so ruin them. Therefore the sage desires what (other men) do not desire, and does not prize things difficult to get; he learns what (other men) do not learn, and turns back to what the multitude of men have passed by. Thus he helps the natural development of all things, and does not dare to act (with an ulterior purpose of his own)."],
  ],
  [ // 65
    ["古之善為道者，非以明民，將以愚之。", "The ancients who showed their skill in practising the Dao did so, not to enlighten the people, but rather to make them simple and ignorant."],
    ["民之難治，以其智多。", "The difficulty in governing the people arises from their having much knowledge."],
    ["故以智治國，國之賊；不以智治國，國之福。", "He who (tries to) govern a state by his wisdom is a scourge to it; while he who does not (try to) do so is a blessing."],
    ["知此兩者亦𥡴式。", "He who knows these two things finds in them also his model and rule."],
    ["常知𥡴式，是謂玄德。", "Ability to know this model and rule constitutes what we call the mysterious excellence (of a governor)."],
    ["玄德深矣，遠矣，與物反矣，然後乃至大順。", "Deep and far-reaching is such mysterious excellence, showing indeed its possessor as opposite to others, but leading them to a great conformity to him."],
  ],
  [ // 66
    ["江海所以能為百谷王者，以其善下之，故能為百谷王。", "That whereby the rivers and seas are able to receive the homage and tribute of all the valley streams, is their skill in being lower than they; - it is thus that they are the kings of them all."],
    ["是以聖人欲上民，必以言下之；欲先民，必以身後之。", "So it is that the sage (ruler), wishing to be above men, puts himself by his words below them, and, wishing to be before them, places his person behind them."],
    ["是以聖人處上而民不重，處前而民不害。", "In this way though he has his place above them, men do not feel his weight, nor though he has his place before them, do they feel it an injury to them."],
    ["是以天下樂推而不厭。", "Therefore all in the world delight to exalt him and do not weary of him."],
    ["以其不爭，故天下莫能與之爭。", "Because he does not strive, no one finds it possible to strive with him."],
  ],
  [ // 67
    ["天下皆謂我道大，似不肖。", "All the world says that, while my Dao is great, it yet appears to be inferior (to other systems of teaching)."],
    ["夫唯大，故似不肖。", "Now it is just its greatness that makes it seem to be inferior."],
    ["若肖久矣。", "If it were like any other (system), for long would its smallness have been known!"],
    ["其細也夫！", ""],
    ["我有三寶，持而保之。", "But I have three precious things which I prize and hold fast."],
    ["一曰慈，二曰儉，三曰不敢為天下先。", "The first is gentleness; the second is economy; and the third is shrinking from taking precedence of others."],
    ["慈故能勇；儉故能廣；不敢為天下先，故能成器長。", "With that gentleness I can be bold; with that economy I can be liberal; shrinking from taking precedence of others, I can become a vessel of the highest honour."],
    ["今舍慈且勇；舍儉且廣；舍後且先；死矣！", "Now-a-days they give up gentleness and are all for being bold; economy, and are all for being liberal; the hindmost place, and seek only to be foremost; - (of all which the end is) death."],
    ["夫慈以戰則勝，以守則固。", "Gentleness is sure to be victorious even in battle, and firmly to maintain its ground."],
    ["天將救之，以慈衛之。", "Heaven will save its possessor, by his (very) gentleness protecting him."],
  ],
  [ // 68
    ["善為士者，不武；善戰者，不怒；善勝敵者，不與；善用人者，為之下。", "He who in (Dao's) wars has skill Assumes no martial port; He who fights with most good will To rage makes no resort. He who vanquishes yet still Keeps from his foes apart; He whose hests men most fulfil Yet humbly plies his art."],
    ["是謂不爭之德，是謂用人之力，是謂配天古之極。", "Thus we say, 'He never contends, And therein is his might.' Thus we say, 'Men's wills he bends, That they with him unite.' Thus we say, 'Like Heaven's his ends, No sage of old more bright.'"],
  ],
  [ // 69
    ["用兵有言：吾不敢為主，而為客；不敢進寸，而退尺。", "A master of the art of war has said, 'I do not dare to be the host (to commence the war); I prefer to be the guest (to act on the defensive). I do not dare to advance an inch; I prefer to retire a foot.'"],
    ["是謂行無行；攘無臂；扔無敵；執無兵。", "This is called marshalling the ranks where there are no ranks; baring the arms (to fight) where there are no arms to bare; grasping the weapon where there is no weapon to grasp; advancing against the enemy where there is no enemy."],
    ["禍莫大於輕敵，輕敵幾喪吾寶。", "There is no calamity greater than lightly engaging in war. To do that is near losing (the gentleness) which is so precious."],
    ["故抗兵相加，哀者勝矣。", "Thus it is that when opposing weapons are (actually) crossed, he who deplores (the situation) conquers."],
  ],
  [ // 70
    ["吾言甚易知，甚易行。", "My words are very easy to know, and very easy to practise;"],
    ["天下莫能知，莫能行。", "but there is no one in the world who is able to know and able to practise them."],
    ["言有宗，事有君。", "There is an originating and all-comprehending (principle) in my words, and an authoritative law for the things (which I enforce)."],
    ["夫唯無知，是以不我知。", "It is because they do not know these, that men do not know me."],
    ["知我者希，則我者貴。", "They who know me are few, and I am on that account (the more) to be prized."],
    ["是以聖人被褐懷玉。", "It is thus that the sage wears (a poor garb of) hair cloth, while he carries his (signet of) jade in his bosom."],
  ],
  [ // 71
    ["知不知上；不知知病。", "To know and yet (think) we do not know is the highest (attainment); not to know (and yet think) we do know is a disease."],
    ["夫唯病病，是以不病。", "It is simply by being pained at (the thought of) having this disease that we are preserved from it."],
    ["聖人不病，以其病病，是以不病。", "The sage has not the disease. He knows the pain that would be inseparable from it, and therefore he does not have it."],
  ],
  [ // 72
    ["民不畏威，則大威至。", "When the people do not fear what they ought to fear, that which is their great dread will come on them."],
    ["無狎其所居，無厭其所生。", "Let them not thoughtlessly indulge themselves in their ordinary life; let them not act as if weary of what that life depends on."],
    ["夫唯不厭，是以不厭。", "It is by avoiding such indulgence that such weariness does not arise."],
    ["是以聖人自知不自見；自愛不自貴。", "Therefore the sage knows (these things) of himself, but does not parade (his knowledge); loves, but does not (appear to set a) value on, himself."],
    ["故去彼取此。", "And thus he puts the latter alternative away and makes choice of the former."],
  ],
  [ // 73
    ["勇於敢則殺，勇於不敢則活。", "He whose boldness appears in his daring (to do wrong, in defiance of the laws) is put to death; he whose boldness appears in his not daring (to do so) lives on."],
    ["此兩者，或利或害。", "Of these two cases the one appears to be advantageous, and the other to be injurious."],
    ["天之所惡，孰知其故？", "But When Heaven's anger smites a man, Who the cause shall truly scan?"],
    ["是以聖人猶難之。", "On this account the sage feels a difficulty (as to what to do in the former case)."],
    ["天之道，不爭而善勝，不言而善應，不召而自來，繟然而善謀。", "It is the way of Heaven not to strive, and yet it skilfully overcomes; not to speak, and yet it is skilful in (obtaining a reply); does not call, and yet men come to it of themselves. Its demonstrations are quiet, and yet its plans are skilful and effective."],
    ["天網恢恢，踈而不失。", "The meshes of the net of Heaven are large; far apart, but letting nothing escape."],
  ],
  [ // 74
    ["民不畏死，奈何以死懼之？", "The people do not fear death; to what purpose is it to (try to) frighten them with death?"],
    ["若使民常畏死，而為奇者，吾得執而殺之，孰敢？", "If the people were always in awe of death, and I could always seize those who do wrong, and put them to death, who would dare to do wrong?"],
    ["常有司殺者殺。", "There is always One who presides over the infliction death."],
    ["夫司殺者，是大匠斲；夫代大匠斲者，希有不傷其手矣。", "He who would inflict death in the room of him who so presides over it may be described as hewing wood instead of a great carpenter. Seldom is it that he who undertakes the hewing, instead of the great carpenter, does not cut his own hands!"],
  ],
  [ // 75
    ["民之飢，以其上食稅之多，是以飢。", "The people suffer from famine because of the multitude of taxes consumed by their superiors. It is through this that they suffer famine."],
    ["民之難治，以其上之有為，是以難治。", "The people are difficult to govern because of the (excessive) agency of their superiors (in governing them). It is through this that they are difficult to govern."],
    ["民之輕死，以其求生之厚，是以輕死。", "The people make light of dying because of the greatness of their labours in seeking for the means of living. It is this which makes them think light of dying."],
    ["夫唯無以生為者，是賢於貴生。", "Thus it is that to leave the subject of living altogether out of view is better than to set a high value on it."],
  ],
  [ // 76
    ["人之生也柔弱，其死也堅強。", "Man at his birth is supple and weak; at his death, firm and strong."],
    ["萬物草木之生也柔脆，其死也枯槁。", "(So it is with) all things. Trees and plants, in their early growth, are soft and brittle; at their death, dry and withered."],
    ["故堅強者死之徒，柔弱者生之徒。", "Thus it is that firmness and strength are the concomitants of death; softness and weakness, the concomitants of life."],
    ["是以兵強則不勝，木強則共。", "Hence he who (relies on) the strength of his forces does not conquer; and a tree which is strong will fill the out-stretched arms, (and thereby invites the feller.)"],
    ["強大處下，柔弱處上。", "Therefore the place of what is firm and strong is below, and that of what is soft and weak is above."],
  ],
  [ // 77
    ["天之道，其猶張弓與？", "May not the Way (or Dao) of Heaven be compared to the (method of) bending a bow?"],
    ["高者抑之，下者舉之；有餘者損之，不足者補之。", "The (part of the bow) which was high is brought low, and what was low is raised up. (So Heaven) diminishes where there is superabundance, and supplements where there is deficiency."],
    ["天之道，損有餘而補不足。", "It is the Way of Heaven to diminish superabundance, and to supplement deficiency."],
    ["人之道，則不然，損不足以奉有餘。", "It is not so with the way of man. He takes away from those who have not enough to add to his own superabundance."],
    ["孰能有餘以奉天下，唯有道者。", "Who can take his own superabundance and therewith serve all under heaven? Only he who is in possession of the Dao!"],
    ["是以聖人為而不恃，功成而不處，其不欲見賢。", "Therefore the (ruling) sage acts without claiming the results as his; he achieves his merit and does not rest (arrogantly) in it: - he does not wish to display his superiority."],
  ],
  [ // 78
    ["天下莫柔弱於水，而攻堅強者莫之能勝，其無以易之。", "There is nothing in the world more soft and weak than water, and yet for attacking things that are firm and strong there is nothing that can take precedence of it; - for there is nothing (so effectual) for which it can be changed."],
    ["弱之勝強，柔之勝剛，天下莫不知，莫能行。", "Every one in the world knows that the soft overcomes the hard, and the weak the strong, but no one is able to carry it out in practice."],
    ["是以聖人云：受國之垢，是謂社稷主；受國不祥，是謂天下王。", "Therefore a sage has said, 'He who accepts his state's reproach, Is hailed therefore its altars' lord; To him who bears men's direful woes They all the name of King accord.'"],
    ["正言若反。", "Words that are strictly true seem to be paradoxical."],
  ],
  [ // 79
    ["和大怨，必有餘怨；安可以為善？", "When a reconciliation is effected (between two parties) after a great animosity, there is sure to be a grudge remaining (in the mind of the one who was wrong). And how can this be beneficial (to the other)?"],
    ["是以聖人執左契，而不責於人。", "Therefore (to guard against this), the sage keeps the left-hand portion of the record of the engagement, and does not insist on the (speedy) fulfilment of it by the other party."],
    ["有德司契，無德司徹。", "(So), he who has the attributes (of the Dao) regards (only) the conditions of the engagement, while he who has not those attributes regards only the conditions favourable to himself."],
    ["天道無親，常與善人。", "In the Way of Heaven, there is no partiality of love; it is always on the side of the good man."],
  ],
  [ // 80
    ["小國寡民。", "In a little state with a small population,"],
    ["使有什伯之器而不用；使民重死而不遠徙。", "I would so order it, that, though there were individuals with the abilities of ten or a hundred men, there should be no employment of them; I would make the people, while looking on death as a grievous thing, yet not remove elsewhere (to avoid it)."],
    ["雖有舟輿，無所乘之，雖有甲兵，無所陳之。", "Though they had boats and carriages, they should have no occasion to ride in them; though they had buff coats and sharp weapons, they should have no occasion to don or use them."],
    ["使民復結繩而用之，甘其食，美其服，安其居，樂其俗。", "I would make the people return to the use of knotted cords (instead of the written characters). They should think their (coarse) food sweet; their (plain) clothes beautiful; their (poor) dwellings places of rest; and their common (simple) ways sources of enjoyment."],
    ["鄰國相望，雞犬之聲相聞，民至老死，不相往來。", "There should be a neighbouring state within sight, and the voices of the fowls and dogs should be heard all the way from it to us, but I would make the people to old age, even to death, not have any intercourse with it."],
  ],
  [ // 81
    ["信言不美，美言不信。", "Sincere words are not fine; fine words are not sincere."],
    ["善者不辯，辯者不善。", "Those who are skilled (in the Dao) do not dispute (about it); the disputatious are not skilled in it."],
    ["知者不博，博者不知。", "Those who know (the Dao) are not extensively learned; the extensively learned do not know it."],
    ["聖人不積，既以為人己愈有，既以與人己愈多。", "The sage does not accumulate (for himself). The more that he expends for others, the more does he possess of his own; the more that he gives to others, the more does he have himself."],
    ["天之道，利而不害；聖人之道，為而不爭。", "With all the sharpness of the Way of Heaven, it injures not; with all the doing in the way of the sage he does not strive."],
  ],
];

const verses = CHAPTERS.map((sentences, ci) => ({
  reference: chapterName(ci + 1),
  text: sentences.map(([zh]) => zh).join('\n'),
  textEn: sentences.map(([, en]) => en).join('\n'),
  chapter: ci + 1,
}));

export const DAODEJING_SETS = [
  {
    id: 'daodejing',
    title: '道德經 · 老子',
    titleEn: 'Dao De Jing · Laozi',
    description: '《道德經》王弼本全八十一章，一章一段，中文逐句對照理雅各（James Legge，1891）英譯。',
    language: 'cuv',
    sourceLang: 'zh',
    builtIn: true,
    verses,
  },
];
